product:
    path:     /
    defaults: { _controller: "DDShopBundle:Product:index" }

product_show:
    path:     /{id}/show
    defaults: { _controller: "DDShopBundle:Product:show" }

product_new:
    path:     /new
    defaults: { _controller: "DDShopBundle:Product:new" }

product_create:
    path:     /create
    defaults: { _controller: "DDShopBundle:Product:create" }
    requirements: { _method: post }

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "DDShopBundle:Product:edit" }

product_update:
    path:     /{id}/update
    defaults: { _controller: "DDShopBundle:Product:update" }
    requirements: { _method: post|put }

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "DDShopBundle:Product:delete" }
    requirements: { _method: post|delete }
delete_src:
    path: /delete_src/{id}
    defaults: { _controller: "DDShopBundle:Product:deleteSrc" }
