<?php

namespace DD\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends EntityRepository
{
    public function findOneByResource ($resource){
        $q = $this->createQueryBuilder('r')
            ->where('r.resource =:resource')
            ->setParameter('resource',$resource)
            ->getQuery();
        return $resource= $q->getSingleResult();
    }
}
