<?php

namespace DD\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    public function findOneByRole ($role){
        $q = $this->createQueryBuilder('r')
                  ->where('r.role =:role')
                  ->setParameter('role',$role)
                  ->getQuery();
        return $role= $q->getSingleResult();



    }
}
