DD\ShopBundle\Entity\Category:
    type: entity
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: category
    manyToOne:
        resource:
            targetEntity: Resource
            inversedBy: category
            joinColumn:
                name: resource_id
                referencedColumnName: id
    table: null
    repositoryClass: DD\ShopBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        flag:
            type: boolean
    lifecycleCallbacks: {  }
