DD\ShopBundle\Entity\Product:
    type: entity
    manyToOne:
        categoty:
            targetEntity: Category
            inversedBy: product
            joinColumn:
                name: category_id
                referencedColumnName: id
    table: null
    repositoryClass: DD\ShopBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        src:
            type: string
            length: 255
        description:
            type: text
        flag:
            type: boolean
        date:
            type: date
        lastdate:
            type: date
    lifecycleCallbacks: {  }
