DD\ShopBundle\Entity\Product:
    type: entity
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
    manyToMany:
        product:
            targetEntity: Product
            joinTable:
                name: Product_Group
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    relations_product_id:
                        referencedColumnName: id


    table: null
    repositoryClass: DD\ShopBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        src:
            type: string
            length: 255
        date:
            type: datetime
        lastdate:
            type: datetime
        flag:
            type: boolean
    lifecycleCallbacks: {  }
